# Generated by Django 6.0.7 on 2026-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_routestop_transportroute_vehicle_attendance_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='privacy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='privacy_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
